<div class="home-page-slider">
    <section class="slider">
        <div class="flexslider">
            <ul class="slides">
                <li>
                    <img src="<?php echo $this->getViewFileUrl('Custom_Module::images/kitchen_adventurer_cheesecake_brownie.jpg');?>" />
                </li>
                <li>
                    <img src="<?php echo $this->getViewFileUrl('Custom_Module::images/kitchen_adventurer_lemon.jpg');?>" />
                </li>
                <li>
                    <img src="<?php echo $this->getViewFileUrl('Custom_Module::images/kitchen_adventurer_donut.jpg');?>" />
                </li>
                <li>
                    <img src="<?php echo $this->getViewFileUrl('Custom_Module::images/kitchen_adventurer_caramel.jpg'); ?>" />
                </li>
            </ul>
        </div>
    </section>
</div>